



# HTTP → HTTPS
server {
    listen 80;
    server_name grandleagueexpert.com www.grandleagueexpert.com;

    return 301 https://$host$request_uri;
}

# HTTPS SERVER
server {
    listen 443 ssl;
    server_name grandleagueexpert.com www.grandleagueexpert.com;
    client_max_body_size 50M;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Content-Security-Policy "frame-ancestors 'self'" always;
    ssl_certificate /etc/letsencrypt/live/grandleagueexpert.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/grandleagueexpert.com/privkey.pem;

    # NEXTAUTH FIX (VERY IMPORTANT)
    location /api/auth/ {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
    }

    # DJANGO API
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    # ADMIN


    location /admin/ {
    proxy_pass http://backend:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto https;

    client_max_body_size 50M;   # 🔥 IMPORTANT (file uploads)
    }

    # STATIC
    location /static/ {
        alias /var/www/staticfiles/;
    }

    # FRONTEND
    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }
}