# HTTP → redirect to HTTPS
server {
    listen 80;
    server_name grandleagueexpert.com www.grandleagueexpert.com;

    return 301 https://$host$request_uri;
}

# HTTPS SERVER
server {
    listen 443 ssl;
    server_name grandleagueexpert.com www.grandleagueexpert.com;

    ssl_certificate /etc/letsencrypt/live/grandleagueexpert.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/grandleagueexpert.com/privkey.pem;

    client_max_body_size 50M;

    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://backend:8000;
    }

    location /admin/ {
        proxy_pass http://backend:8000;
    }

    location /static/ {
        alias /var/www/staticfiles/;
    }
}
ubuntu@ip-172-26-0-234:~/gle-prod$ 
Preparing to unpack .../28-libgomp1_14