# Generated by Django 6.0.3 on 2026-04-05 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_1", models.CharField(max_length=120, verbose_name="Team 1")),
                ("team_2", models.CharField(max_length=120, verbose_name="Team 2")),
                (
                    "match_name",
                    models.CharField(max_length=255, verbose_name="Match Name"),
                ),
                ("match_date", models.DateTimeField(verbose_name="Match Date")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "ordering": ["-match_date"],
            },
        ),
        migrations.CreateModel(
            name="FreeContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="free_content/", verbose_name="File"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("image", "Image")],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_contents",
                        to="matches.match",
                        verbose_name="Match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Free Content",
                "verbose_name_plural": "Free Content",
            },
        ),
        migrations.CreateModel(
            name="PremiumContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Expert Analysis")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_contents",
                        to="matches.match",
                        verbose_name="Match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Premium Content",
                "verbose_name_plural": "Premium Content",
            },
        ),
    ]
