# Generated by Django 6.0.3 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="premiumcontent",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="premium_content/", verbose_name="Image"),
        ),
    ]
