# Generated by Django 6.0.3 on 2026-04-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchpurchase",
            name="is_subscription",
            field=models.BooleanField(default=False, verbose_name="Is Subscription"),
        ),
        migrations.AddField(
            model_name="matchpurchase",
            name="subscription_end",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Subscription End",
            ),
        ),
        migrations.AddField(
            model_name="matchpurchase",
            name="subscription_start",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Subscription Start",
            ),
        ),
        migrations.AlterField(
            model_name="matchpurchase",
            name="match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="matches.match",
                verbose_name="Match",
            ),
        ),
    ]
