# Generated by Django 6.0.3 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_matchpurchase_subscription_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_price",
                    models.IntegerField(
                        default=3900,
                        help_text="Price per match in paise (3900 = ₹39)",
                    ),
                ),
                (
                    "monthly_price",
                    models.IntegerField(
                        default=49900,
                        help_text="Monthly price in paise (49900 = ₹499)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pricing Configuration",
                "verbose_name_plural": "Pricing Configurations",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
