# Generated by Django 6.0.3 on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_pricingconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingconfig",
            name="enable_match",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="enable_monthly",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="enable_weekly",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="monthly_offer_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="monthly_original_price",
            field=models.IntegerField(default=49900, help_text="Strikethrough price"),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="weekly_offer_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="weekly_original_price",
            field=models.IntegerField(default=19900, help_text="Strikethrough price"),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="weekly_price",
            field=models.IntegerField(default=12900, help_text="Offer price in paise"),
        ),
    ]
