# Generated by Django 6.0.3 on 2026-04-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_extend_pricingconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("subscription", "Monthly")],
                        max_length=20,
                        verbose_name="Plan Type",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateTimeField(db_index=True, verbose_name="End Date"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "last_payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=128,
                        verbose_name="Last Payment ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Subscription",
                "verbose_name_plural": "User Subscriptions",
            },
        ),
        migrations.CreateModel(
            name="ProcessedPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Payment ID"
                    ),
                ),
                (
                    "order_id",
                    models.CharField(db_index=True, max_length=128, verbose_name="Order ID"),
                ),
                (
                    "plan_type",
                    models.CharField(max_length=20, verbose_name="Plan Type"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payments",
                        to="matches.match",
                        verbose_name="Match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processed Payment",
                "verbose_name_plural": "Processed Payments",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
