# Generated by Django 6.0.3 on 2026-04-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(default=False, verbose_name="Is Premium"),
        ),
        migrations.AddField(
            model_name="user",
            name="premium_expiry",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Premium Expiry"
            ),
        ),
    ]
