# Generated by Django 6.0.3 on 2026-04-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_premium_user_premium_expiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdatePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "body",
                    models.TextField(
                        help_text="Use line breaks and bullet-style text for clarity"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Update Post",
                "verbose_name_plural": "Update Posts",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="UserUpdateStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_statuses",
                        to="users.updatepost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Update Status",
                "verbose_name_plural": "User Update Statuses",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "update"), name="unique_user_update_status"
                    )
                ],
            },
        ),
    ]
